### ISSUE TITLE
Enhancement (additional): add sleep into the request on the server side, analyze tha changes

### ISSUE THREAD

**Issue by akurilov** [vladislav-kulakovsky/Java-RMI-client-server-with-concurrency#3]
- Add 1 millisecond sleep into the server's method returning the random number
- Rerun the test and plot the new chart
- Add 3 milliseconds sleep instead of 1 ms
- Rerun the test and plot the new chart
- Compare and analyze the resulting charts (no sleep, 1ms sleep, 3ms sleep). Answer the following question: how behaves the optimal thread count (which corresponds to the max rate peak) while the request duration increases?

**Comment by vladislav-kulakovsky** [comment]
@akurilov 
I have done this and the results is as follows:
### with 1ms sleep
![result_sleep_1ms](https://raw.githubusercontent.com/vladislav-kulakovsky/Java-RMI-client-server-with-concurrency/master/doc/pictures/result_sleep_1ms.png)
**We can see that if we have latency then the following occurs:**
The dependency begins to tend to linear, as when connecting a new client thread, a thread is created on the server (this is seen from jvisualvm) and when the sleep method is called, the thread is blocked. It turns out that because of this delay the number of requests is noticeably reduced, but if you increase the number of threads, the corresponding number of threads will be launched on the server. Since the scheduler will toggle them, each thread will process approximately the same number of requests, respectively, as the number of threads increases, the number of requests increases directly in proportion.
![jvisualvm](https://raw.githubusercontent.com/vladislav-kulakovsky/Java-RMI-client-server-with-concurrency/master/doc/pictures/jvisualvm_sleep3ms_8threads.png)
**In russian:**
Зависимость начинает стремиться к линейной, так как при подключении нового клиентского потока создается поток на сервере (это видно из jvisualvm) и при вызове метода sleep поток блокируется. Получается, что из-за этой задержки количество запросов заметно уменьшается, но если увеличить число потоков, то на сервере будет запущено соответствующее количество потоков. Так как планировщик будет их переключать, то каждый поток обработает примерно одинаковое количество запросов, соответсвенно с увеличением числа потоков, увеличивается количество запросов прямопропорционально.

### with 3ms sleep
![result_sleep_3ms](https://raw.githubusercontent.com/vladislav-kulakovsky/Java-RMI-client-server-with-concurrency/master/doc/pictures/result_sleep_3ms.png) 
If the delay is increased to three milliseconds, the phenomenon described above becomes more pronounced and becomes more or less linear.
**In russian:**
При увеличении задержки до трех миллисекунд описанное выше явление проявляется сильнее и зависимоть становиться практически линейной.
